configProperties:
  version: v2

application:
  name: zadig
  manifestType: helmRepo
  services:
    - name: aslan
      serviceType: deployment
      containers:
        - name: aslan
          dev:
            gitUrl: https://github.com/koderover/zadig.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:zadig
            workDir: /root/nocalhost-dev
            shell: "/bin/zsh"
            command:
              run: ["go", "run", "./cmd/aslan/main.go"]
              debug: ["dlv", "debug", "./cmd/aslan/main.go", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient"]
            debug:
              remoteDebugPort: 2345